### ISSUE TITLE
npm run start is OK ,but npm run publish will alert that can not find module simple-plist

### ISSUE THREAD

**Issue by avboy1337** [bytedance/debugtron#17]
![image](https://user-images.githubusercontent.com/5463104/204306281-0ece6336-1224-4eae-aabc-18cf6749e431.png)

I use steps as following:

choco install visualstudio2019-workload-vctools -Y
npm config set msvs_version 2019 --global
npm i
npm run start
npm run publish

**Comment by avboy1337** [comment]
sorry solved!

**Comment by jerry4718** [comment]
It's strange that I still have this problem when I build on Linux
