### ISSUE TITLE
Visual Studio Installer directory is wrong

### ISSUE THREAD

**Issue by EzeKoren** [bytedance/debugtron#5]
When running `npm start` this is the output I get, and no programs can be launched from Debugtron. For context, `E:\debugtron\` is the debugtron repo path, and `C:\Program Files (x86)\Microsoft Visual Studio\Installer\` is the Visual Studio Installer path.

```
[Error: ENOENT: no such file or directory, scandir 'E:\debugtron\"C:\Program Files (x86)\Microsoft Visual Studio\Installer"'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'E:\\debugtron\\"C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer"'
}
```

Windows 10 version 2004 build 19041.329

**Comment by EzeKoren** [comment]
What I assume is happening is that the program accidentally appends the VS Installer path to the running path

**Comment by pd4d10** [comment]
Thanks for your feedback!

According to the error message, it seems the install path read from the registry has a little problem. The heading and trailing quotes should be removed.

Could you please try to change the following code

https://github.com/bytedance/debugtron/blob/d56c68c6fe2e47ce799e1d623bfce0fc684b91c0/src/main/win.ts#L133

 to

```js
installDir = installLocation.data.replace(/^["']+|["']+$/g, '')
```

**Comment by EzeKoren** [comment]
Thank you! That solved the issue

**Comment by pd4d10** [comment]
Great! I'll submit this fix later. Thanks for your report!

I'm going to close this issue. Feel free to reopen it if there are other problems.
